services:
  backend:
    build:
      context: ./hasthakala-server
      dockerfile: Dockerfile
    ports:
      - "5050:5000"
    volumes:
      - ./hasthakala-server:/app
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
