# STEP 1: Build the React app
FROM node:18 AS build

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

# STEP 2: Serve the built app using Nginx
FROM nginx:alpine

# Remove the default nginx static files
RUN rm -rf /usr/share/nginx/html/*

# Copy build output from previous step
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
